### ISSUE TITLE
iosxr_interfaces does not work on interfaces that are not in running-config

### ISSUE THREAD

**Issue by NilashishC** [ansible-collections/cisco.iosxr#106]
##### SUMMARY
- For interfaces that physically exists but do not have an entry in running-config, the iosxr_interfaces module does not make any changes.
- This also means, the module cannot set "preconfigure" interfaces it those are not in running-config already.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iosxr_interfaces.py
possibly other iosxr interface modules too.

##### ANSIBLE VERSION
Tested against latest version of cisco.iosxr collection.

##### OS / ENVIRONMENT
IOS-XR 6.1.2
IOS-XR 6.1.3

##### STEPS TO REPRODUCE
```yaml
- name: Remove interfaces from config before actual testing
  cisco.iosxr.iosxr_config: &rem
    lines:
      - no interface GigabitEthernet 0/0/0/1
      - no interface GigabitEthernet 0/0/0/2
      - no interface GigabitEthernet 0/0/0/4
    match: none        

- name: Merge base interfaces configuration
  cisco.iosxr.iosxr_interfaces:
    config:
      - name: GigabitEthernet0/0/0/1
        description: Configured by Ansible
        mtu: 110
        enabled: true
        duplex: half
      - name: GigabitEthernet0/0/0/2
        description: Configured by Ansible
        mtu: 2800
        speed: 100
        enabled: true
        duplex: full
    state: merged
```
The second task will return changed=False.

##### EXPECTED RESULTS
```
changed: [iosxr-02] => changed=true
  after:
  - description: Configured by Ansible
    duplex: half
    enabled: true
    mtu: 110
    name: GigabitEthernet0/0/0/1
  - description: Configured by Ansible
    duplex: full
    enabled: true
    mtu: 2800
    name: GigabitEthernet0/0/0/2
    speed: 100
  before: []
  commands:
  - interface GigabitEthernet0/0/0/1
  - description Configured by Ansible
  - mtu 110
  - duplex half
  - no shutdown
  - interface GigabitEthernet0/0/0/2
  - description Configured by Ansible
  - mtu 2800
  - speed 100
  - duplex full
  - no shutdown
```

##### ACTUAL RESULTS
```
ok: [iosxr-02] => changed=false
  before: []
  commands: []
  invocation:
    module_args:
      config:
      - description: Configured by Ansible
        duplex: half
        enabled: true
        mtu: 110
        name: GigabitEthernet0/0/0/1
        speed: null
      - description: Configured by Ansible
        duplex: full
        enabled: true
        mtu: 2800
        name: GigabitEthernet0/0/0/2
        speed: 100
      running_config: null
      state: merged
```
