### ISSUE TITLE
Add available_network_resources key in iosxr_facts module

### ISSUE THREAD

**Issue by trishnaguha** [ansible-collections/cisco.iosxr#119]
- The key will return the list of all the RM resources available for the platform.
- This implementation doesn't affect the current functionality of the iosxr_facts module and users can use the iosxr_facts module in the same way as they were before.

Current behavior:
```
---
- name: Fatch facts
  hosts: iosxr
  gather_facts: no
  collections:
    - cisco.iosxr
  
  tasks:
    - name: Get basic facts 
      iosxr_facts:
        gather_subset:
          - '!all'
```
output
```
ok: [10.8.8.69] => {
    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "10",
        "ansible_net_image": "bootflash:disk0/xrvr-os-mbi-6.1.3/mbixrvr-rp.vm",
        "ansible_net_model": "IOS XRv",
        "ansible_net_python_version": "3.9.2",
        "ansible_net_system": "iosxr",
        "ansible_net_version": "6.1.3[Default]",
        "ansible_network_resources": {},
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": false,
            "gather_network_resources": null,
            "gather_subset": [
                "!all"
            ],
            "provider": null
        }
    }
}
```
`After implementation of available_network_resources`
`Sample Playbook`:
```
---
- name: Get the list of  available resource Modules
  hosts: iosxr
  gather_facts: no
  collections:
    - cisco.iosxr
  
  tasks:
    - name: Get the list of available network resources for Cisco IOS-XR 6.1.3  and avoid fetching resource facts
      iosxr_facts:
        gather_subset:
          - '!all'
        available_network_resources: true
```
Result: 
```
ok: [10.8.8.69] => {
    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "10",
        "ansible_net_image": "bootflash:disk0/xrvr-os-mbi-6.1.3/mbixrvr-rp.vm",
        "ansible_net_model": "IOS XRv",
        "ansible_net_python_version": "3.9.2",
        "ansible_net_system": "iosxr",
        "ansible_net_version": "6.1.3[Default]",
        "ansible_network_resources": {},
        "available_network_resources": [
            "acl_interfaces",
            "acls",
            "bgp_address_family",
            "bgp_global",
            "bgp_neighbor_address_family",
            "interfaces",
            "l2_interfaces",
            "l3_interfaces",
            "lacp",
            "lacp_interfaces",
            "lag_interfaces",
            "lldp_global",
            "lldp_interfaces",
            "ospf_interfaces",
            "ospfv2",
            "ospfv3",
            "static_routes"
        ],
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": true,
            "gather_network_resources": null,
            "gather_subset": [
                "!all"
            ],
            "provider": null
        }
    }
}
```
