### ISSUE TITLE
IOSXR Patches Seem To Be Missing In Collection version 2.3

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#192]
##### SUMMARY
bugfix_138 should be present in Ansible Network Collection for Cisco IOSXR version 2.2+ but seems to be absent in collection 2.3.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
collections/ansible_collections/cisco/iosxr/plugins/cliconf/iosxr.py

##### ANSIBLE VERSION
[USER@XXXX_RHEL8 sips-cable-test]$ ansible-galaxy --version

ansible-galaxy 2.9.23

  config file = /home/USER/.ansible.cfg

  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']

  ansible python module location = /usr/lib/python3.6/site-packages/ansible

  executable location = /usr/bin/ansible-galaxy

  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

[USER@XXXX_RHEL8 sips-cable-test]$

##### COLLECTION VERSION
"ansible-galaxy collection list <namespace>.<collection>"  does not run properly, it errs out:
```
[USER@XXXX_RHEL8 sips-cable-test]$ ansible-galaxy collection list collections/ansible_collections/cisco.iosxr

usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...

ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

[USER@XXXX_RHEL8 sips-cable-test]$ 
```

##### CONFIGURATION
```
[USER@XXXX_RHEL8 sips-cable-test]$ ansible-config dump --only-changed

GALAXY_IGNORE_CERTS(/home/USER/.ansible.cfg) = True

GALAXY_SERVER_LIST(/home/USER/.ansible.cfg) = ['published_repo', 'rh-certified_repo']

[USER@XXXX_RHEL8 sips-cable-test]$
```

##### OS / ENVIRONMENT
Tower Version 3.7.3
Network device NCS55A-01 running IOSXR 7.2.2

##### STEPS TO REPRODUCE
```
sips-cable-test is chosen and errs out because a comment is left.  This should not happen because the fix for this issue should be part of the 2.3 collection: https://github.com/ashwini-mhatre/cisco.iosxr/tree/bugfix_138
```

##### EXPECTED RESULTS
For network devices that do not support comments the comment should be ignored.

##### ACTUAL RESULTS
For network devices that do not support comments the comment is attempted to be written with the set
of changes to the network device and the device does not commit any of the changes because a comment
is used when it is not supported by IOSXR.

**Comment by ashwini-mhatre** [comment]
@digitalfiend64 
Today I tested iosxr_config module with comment on NCS5500 device with cisco.iosxr 2.4.0 and 2.5.0 collection.Still I am not able to reproduce this bug. following is the system details on which I have tested it. 
```
ansible_collections) prramoor @ ~/Ansible/iosxr $ ansible-galaxy collection list

 

# /Users/prramoor/.pyenv/versions/3.8.0/envs/ansible_collections/lib/python3.8/site-packages/ansible_collections

Collection                    Version

----------------------------- -------

cisco.iosxr                   2.4.0  


 # /Users/prramoor/.pyenv/versions/3.8.0/envs/ansible_collections/lib/python3.8/site-packages/ansible_collections

Collection                    Version

----------------------------- -------

cisco.iosxr                   2.5.0  


 

RP/0/RP0/CPU0:test3#show version

Wed Nov 10 07:35:11.710 UTC

Cisco IOS XR Software, Version 7.2.2

Copyright (c) 2013-2021 by Cisco Systems, Inc.

 

Build Information:

Built By     : ingunawa

Built On     : Mon Jan 25 21:52:54 PST 2021

Built Host   : iox-ucs-013

Workspace    : /auto/srcarchive15/prod/7.2.2/ncs5500/ws

Version      : 7.2.2

Location     : /opt/cisco/XR/packages/

Label        : 7.2.2

 

cisco NCS-5500 () processor

System uptime is 21 hours 19 minutes

 

 

 

RP/0/RP0/CPU0:test3#show platform

Wed Nov 10 07:35:45.341 UTC

Node              Type                       State             Config state

--------------------------------------------------------------------------------

0/RP0/CPU0        NCS-5501(Active)           IOS XR RUN        NSHUT

0/RP0/NPU0        Slice                      UP               

0/FT0             NCS-1RU-FAN-FW             OPERATIONAL       NSHUT

0/FT1             NCS-1RU-FAN-FW             OPERATIONAL       NSHUT

0/PM0             NCS-1100W-ACFW             OPERATIONAL       NSHUT

0/PM1             NCS-1100W-ACFW             FAILED            NSHUT

RP/0/RP0/CPU0:test3#
```

following is the playbook which I executed on iosxr
```
- name: IOS XR comment and commit config testing on 7.2.2 image
  hosts: iosxr
  gather_facts: no
  connection: network_cli

  tasks:
    - name: configure device with a label and a comment
      register: result
      cisco.iosxr.iosxr_config:
        lines:
          - router bgp 1
        comment: this is test comment
        label: label1

    - name: configure device with a comment
      register: result
      cisco.iosxr.iosxr_config:
          lines:
            - hostname test1
          comment: this is test2 comment

    - name: configure device with a label and default comment
      register: result
      cisco.iosxr.iosxr_config:
          lines:
            - hostname test2
```
