### ISSUE TITLE
Unable to un shut BGP neighbor when setting the shutdown's 'set' parameter to false

### ISSUE THREAD

**Issue by ahegewald257** [ansible-collections/cisco.iosxr#197]
#####SUMMARY

Trying to use the iosxr_bgp_global module to perform a shutdown and no shutdown on ASRv9K router, using the boolean'set' 
parameter to true successfully shuts the BGP session down however setting the value to false has no impact on the 
router.

#####ISSUE TYPE

Bug Report

#####COMPONENT NAME

cisco.iosxr.iosxr_bgp_global

#####ANSIBLE VERSION
'''
ansible [core 2.11.4] 
  config file = /home/ahegewal/ansible/playbooks/traffico/ansible.cfg
  configured module search path = ['/home/ahegewal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ahegewal/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 2.11.3
  libyaml = True
'''  
#####COLLECTION VERSION
```
Collection            Version
--------------------- -------
ansible.netcommon     2.5.0  
ansible.posix         1.3.0  
ansible.utils         2.4.0  
chocolatey.chocolatey 1.1.0  
cisco.ios             2.4.0  
cisco.iosxr           2.6.0  
cisco.nso             1.0.3  
community.crypto      1.9.2  
community.docker      1.9.1  
community.general     3.6.0  
community.mongodb     1.3.1  
community.mysql       2.1.1  
community.rabbitmq    1.1.0  
juniper.device        1.0.0  
```

#####CONFIGURATION
```
DEFAULT_HOST_LIST(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = ['/home/ahegewal/ansible/playbooks/traffico/inventory']
DEFAULT_LOG_PATH(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = /home/ahegewal/ansible/playbooks/traffico/ansible.log
DEFAULT_STDOUT_CALLBACK(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = False
INTERPRETER_PYTHON(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = ../../env/bin/python3
PARAMIKO_LOOK_FOR_KEYS(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = 28800
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = 180
PERSISTENT_CONNECT_TIMEOUT(/home/ahegewal/ansible/playbooks/traffico/ansible.cfg) = 28800
```

##### OS / ENVIRONMENT
Cisco ASRv9K IOS XR version: 6.6.3 
Fedora release 34 (Thirty Four)

##### STEPS TO REPRODUCE

```

Router BGP session is shutdown,

router bgp 5511
 neighbor 10.50.50.1
  use neighbor-group IPTRAN.TESTCUST4-LD543210
  timers 30 180
  shutdown
 !
!
---

- name: "BGP Playbook"
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: routers

    - name: No Shutdown BGP Session
      cisco.iosxr.iosxr_bgp_global:
        state: merged
        config:
          as_number: 5511
          neighbors:
             - neighbor: 10.50.50.1
               shutdown:
                  set: no
      register: print_output
```

##### EXPECTED RESULTS
Expect the BGP session to no longer be shutdown.

##### ACTUAL RESULTS
The configuration on the router remains unchanged.
```
TASK [No Shutdown BGP Session] **********************************************************************************************************************
task path: /home/ahegewal/ansible/playbooks/traffico/import_bgp.yml:55
redirecting (type: terminal) ansible.builtin.iosxr to cisco.iosxr.iosxr
redirecting (type: cliconf) ansible.builtin.iosxr to cisco.iosxr.iosxr
<192.168.1.125> attempting to start connection
<192.168.1.125> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/local/bin/ansible-connection
<192.168.1.125> found existing local domain socket, using it!
<192.168.1.125> invoked shell using ssh_type: paramiko
<192.168.1.125> ssh connection done, setting terminal
<192.168.1.125> loaded terminal plugin for network_os iosxr
<192.168.1.125> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.1.125> firing event: on_open_shell()
<192.168.1.125> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.1.125> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.1.125> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.1.125> ssh connection has completed successfully
<192.168.1.125> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.1.125> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.1.125> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<192.168.1.125> updating play_context for connection
<192.168.1.125> 
<192.168.1.125> local domain socket path is /home/ahegewal/.ansible/pc/e76f08457e
redirecting (type: action) cisco.iosxr.iosxr_bgp_global to cisco.iosxr.iosxr
redirecting (type: action) cisco.iosxr.iosxr_bgp_global to cisco.iosxr.iosxr
<192.168.1.125> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<192.168.1.125> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<192.168.1.125> ESTABLISH LOCAL CONNECTION FOR USER: ahegewal
<192.168.1.125> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2 `"&& mkdir "` echo /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2/ansible-tmp-1639947978.6237948-370580-159619735287264 `" && echo ansible-tmp-1639947978.6237948-370580-159619735287264="` echo /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2/ansible-tmp-1639947978.6237948-370580-159619735287264 `" ) && sleep 0'
Using module file /home/ahegewal/.ansible/collections/ansible_collections/cisco/iosxr/plugins/modules/iosxr_bgp_global.py
<192.168.1.125> PUT /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2/tmpeb4v2sm7 TO /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2/ansible-tmp-1639947978.6237948-370580-159619735287264/AnsiballZ_iosxr_bgp_global.py
<192.168.1.125> EXEC /bin/sh -c 'chmod u+x /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2/ansible-tmp-1639947978.6237948-370580-159619735287264/ /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2/ansible-tmp-1639947978.6237948-370580-159619735287264/AnsiballZ_iosxr_bgp_global.py && sleep 0'
<192.168.1.125> EXEC /bin/sh -c '/usr/bin/python3 /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2/ansible-tmp-1639947978.6237948-370580-159619735287264/AnsiballZ_iosxr_bgp_global.py && sleep 0'
<192.168.1.125> EXEC /bin/sh -c 'rm -f -r /home/ahegewal/.ansible/tmp/ansible-local-3703140u5bwcp2/ansible-tmp-1639947978.6237948-370580-159619735287264/ > /dev/null 2>&1 && sleep 0'
changed: [labtr0] => changed=true 
  after:
    as_number: '5511'
    bgp:
      default:
        local_preference: 50
    neighbors:
    - neighbor: 10.50.50.1
      shutdown:
        set: true
      timers:
        holdtime: 180
        keepalive_time: 30
  before:
    as_number: '5511'
    bgp:
      default:
        local_preference: 50
    neighbors:
    - neighbor: 10.50.50.1
      shutdown:
        set: true
      timers:
        holdtime: 180
        keepalive_time: 30
  commands:
  - router bgp 5511
  - neighbor 10.50.50.1
  - shutdown
  invocation:
    module_args:
      config:
        as_number: '5511'
        bfd: null
        bgp: null
        default_information: null
        default_metric: null
        graceful_maintenance: null
        ibgp: null
        mpls: null
        mvpn: null
        neighbors:
        - advertisement_interval: null
          bfd: null
          bmp_activate: null
          capability: null
          cluster_id: null
          description: null
          dmz_link_bandwidth: null
          dscp: null
          ebgp_multihop: null
          ebgp_recv_extcommunity_dmz: null
          ebgp_send_extcommunity_dmz: null
          egress_engineering: null
          enforce_first_as: null
          graceful_maintenance: null
          graceful_restart: null
          ignore_connected_check: null
          keychain: null
          local: null
          local_as: null
          log: null
          neighbor: 10.50.50.1
          origin_as: null
          receive_buffer_size: null
          remote_as: null
          send_buffer_size: null
          session_open_mode: null
          shutdown:
            inheritance_disable: null
            set: false
          tcp: null
          timers: null
          ttl_security: null
          update: null
          update_source: null
        nsr: null
        rpki: null
        socket: null
        timers: null
        update: null
        vrfs: null
      running_config: null
      state: merged

```

**Comment by ashwini-mhatre** [comment]
@ahegewald257 could you please use overridden or replaced state with following config.
```
as_number: '5511'
    bgp:
      default:
        local_preference: 50
    neighbors:
    - neighbor: 10.50.50.1
      timers:
        holdtime: 180
        keepalive_time: 30
```
merge state is designed in such a way that it should not remove any config.
