### ISSUE TITLE
iosxr_config commit confirmed

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#199]
##### SUMMARY
The requirement is to have the module cisco.iosxr.iosxr_config perform a “commit confirmed” on Cisco IOS-XR routers instead of default commit on module. The reason we would need this feature is if we believe that upon making changes to a router, we might lose management connectivity (ssh blocked by a recently implemented policy or missing/incorrect return route), we want the router to rollback configuration automatically after a certain amount time of specified time has elapsed (typically 30-180 seconds).

How ‘commit confirmed’ works:
Upon the first commit (i.e. commit confirmed), full configuration is committed to the router. Based on the time period given in command ‘commit confirmed’,  a second “commit” must be issued before the specified timer has run out for change to be successful. If a second commit is not issued, changes are rollbacked automatically.

##### ISSUE TYPE
- Feature Request

##### COMPONENT NAME
cisco.iosxr.iosxr_config

##### ADDITIONAL INFORMATION
Team is thinking best way to add feature would be to provide an additional parameter under existing module cisco.iosxr.iosxr_config. Parameter value would be an integer. This value aligns with the time period of commit confirmed command

Cisco command:

commit confirmed < integer >

New Parameter:

‘commit_confirmed: int’

Team is still trying to determine best test case module could perform to determine if change was successful. Below is an idea we had:

To determine if configuration was successful a test cases must be performed against router. Team is thinking best test case would be to have Ansible flush its connection to device, similar to ‘meta: rest connection’. If Ansible can reconnect to router within time allotted of commit confirmed command, router must still be active. Module could then issue second commit with appropriate label and close task as successful.

If router cannot reestablish connection within time given, router will automatically undo change and router would comeback online as no second commit was made in time period. Router should reconnect based on rest connection. Once it does, module could then mark change as failed.

```yaml

##Inventory

---
all:
  vars:
    ansible_connection: "network_cli"
  children:
    iosxr:
      vars:
        ansible_network_os: "iosxr"
      hosts:
        HRP-01:

## Playbook
---
- name: IOXSR Commit Confirmed
  hosts: iosxr
  gather_facts: false

  tasks:
    - name: Configure iosxr
      cisco.iosxr.iosxr_config:
        src: templates/commit_configure.j2
        commit_confirmed: 60
        label: "Testing commit for iosxr commit confirmed"
      register: result
```
