### ISSUE TITLE
iosxr_prefix_lists support for variable prefix length to be matched

### ISSUE THREAD

**Issue by nleiva** [ansible-collections/cisco.iosxr#229]
##### SUMMARY

`iosxr_prefix_lists` does not support variable prefix length matching, which makes it inconsistent with `nxos_prefix_lists` and `ios_prefix_lists` which both have it.

This is something that Cisco IOS XR allows you to configure: 

```bash
# permit 2001::/32 ?
  eq    Exact prefix length to be matched
  ge    Minimum prefix length to be matched
  le    Maximum prefix length to be matched
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cisco.iosxr.iosxr_prefix_lists

##### ADDITIONAL INFORMATION

To make it consistent with IOS and NX-OS resource modules, we would need to implement `ge` and `le`. Bonus if you move the `description` one level up, so we can pass the following config uncommented to the module.

```yaml
  - afi: ipv6
    prefix_lists:
      - name: IPv6-Prefix-List
        # description: IPv6 Prefix List # iosxr
        entries:
          - action: deny
            prefix: 2001:DB8:0:4::/64
            # ge: 80 # iosxr
            # le: 100 # iosxr
            sequence: 20
```
