### ISSUE TITLE
Additional IOSXR Paramaters

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#244]
confirmed

##### SUMMARY
Request ALL current and future iosxr resource modules support the following parameters (similar to iosxr_config). These parameters are essential when configuring iosxr devices and being able to control commits. Commit Labels are used for rollback on iosxr devices. I believe this would be updated under cisco/iosxr/plugins/module_utils/network/iosxr/argspec

- comment
- disable_default_comment
- exclusive
- label

For additional details behind parameters, please compare to cisco.iosxr.iosxr_config module - https://docs.ansible.com/ansible/latest/collections/cisco/iosxr/iosxr_config_module.html#ansible-collections-cisco-iosxr-iosxr-config-module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Request the following modules contain above parameters:

- cisco.iosxr.iosxr_interfaces
- cisco.iosxr.iosxr_l2_interfaces
- cisco.iosxr.iosxr_l3_interfaces
- cisco.iosxr.iosxr_lacp_interfaces
- cisco.iosxr.iosxr_lag_interfaces
- cisco.iosxr.iosxr_lldp_interfaces
- cisco.iosxr.iosxr_ospf_interfaces
- cisco.iosxr.iosxr_acls
- cisco.iosxr.iosxr_bgp_address_family
- cisco.iosxr.iosxr_bgp_global module
- cisco.iosxr.iosxr_bgp_neighbor_address_family module
- cisco.iosxr.iosxr_lacp
- cisco.iosxr.iosxr_lldp_global
- cisco.iosxr.iosxr_ntp_global
- cisco.iosxr.iosxr_ospfv2
- cisco.iosxr.iosxr_ospfv3
- cisco.iosxr.iosxr_prefix_lists
- cisco.iosxr.iosxr_snmp_server
- cisco.iosxr.iosxr_static_routes

##### ADDITIONAL INFORMATION

Parameters would be supplied under module similar to config and state. Parameters are needed to link an iosxr change to a specific commit / label. Commit labels can be used for rollback using iosxr functionality.

Example:

```yaml
- name: Merge provided configuration with device configuration
  cisco.iosxr.iosxr_l3_interfaces:
    config:
      - name: GigabitEthernet0/0/0/2
        ipv4:
          - address: 192.168.0.1/24
      - name: GigabitEthernet0/0/0/3
        ipv4:
          - address: 192.168.2.1/24
            secondary: true
    state: merged
    label: "configure_l3_intf"
    disable_default_comment: true
    exclusive: true
```

Commit label must be created under config task.

Example of how to leverage a commit label:

```yaml
- name: Rollback L3 interface configurations
   cisco.iosxr.iosxr_command:
     commands: "rollback configuration configure_l3_intf"
```

**Comment by KB-perByte** [comment]
Hey @digitalfiend64,
commit confirmed is a cliconf option which shall can be used per play or per task to define a commit comment or label
example playbook - 
```
  tasks:
    - name: Interface play
      vars:
        ansible_iosxr_commit_confirmed: true
        ansible_iosxr_commit_confirmed_timeout: 30
        ansible_iosxr_commit_confirmed_label: lblInterface
      cisco.iosxr.iosxr_interfaces:
        config:
          - name: GigabitEthernet0/0/0/2
            description: Configured by Ansible RM play
          - name: GigabitEthernet0/0/0/3
            description: Configured by Ansible RM play 2
        state: merged

    - name: Logging play
      vars:
        ansible_iosxr_commit_confirmed: true
        ansible_iosxr_commit_confirmed_timeout: 30
        ansible_iosxr_commit_confirmed_label: lblLogging
      cisco.iosxr.iosxr_logging_global:
        state: merged
        config:
          buffered:
            severity: errors
          correlator:
            buffer_size: 1024
```
checking the commit confirmed per task as:

```
RP/0/RP0/CPU0:Rxtr1#show configuration commit list
SNo. Label/ID              User      Line                Client      Time Stamp
~~~~ ~~~~~~~~              ~~~~      ~~~~                ~~~~~~      ~~~~~~~~~~
1    lblLogging            ansible   vty0:node0_RP0_CPU  CLI         Wed Jun  8 10:14:15 2022
2    lblInterface          ansible   vty0:node0_RP0_CPU  CLI         Wed Jun  8 10:14:04 2022
```
it shall not be a part of every module's argspec it can be used as supplied variables per task
Regards
