### ISSUE TITLE
iosxr_config lines: removes duplicate config lines

### ISSUE THREAD

**Issue by PapaRobba** [ansible-collections/cisco.iosxr#246]
##### SUMMARY

When using the iosxr_config lines: option, duplicate lines of config are removed before being passed to the device. This doesn't happen using the src: file option.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_config
##### ANSIBLE VERSION

```paste below
ansible [core 2.11.5] 
  config file = /home/user/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/scripts/py/junos-pyez/venv/lib64/python3.6/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/scripts/py/junos-pyez/venv/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 2.11.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
cisco.iosxr 3.0.0  
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

CentOS 3.10.0-1160.59.1.el7.x86_64

##### STEPS TO REPRODUCE

```yaml
    - name: policy #1
      iosxr_config:
        lines:
          - "route-policy POLICY1($SID)"
          - "set community COMMUNITY1"
          - "set label-index $SID"
          - "end-policy"
          - "route-policy POLICY2"
          - "pass"
          - "end-policy"
        match: none
```

##### EXPECTED RESULTS

```
+  route-policy POLICY1($SID)
+    set community COMMUNITY1
+    set label-index $SID
+  end-policy
+  route-policy POLICY2
+    pass
+  end-policy
end
```

##### ACTUAL RESULTS

The playbook fails because it tries to execute 'show commit changes diff' at the wrong hierarchy. In this case, since 'end-policy' was already in route-policy POLICY1, the 'end-policy' in route-policy POLICY2 isn't executed. This leaves the prompt at the '(config-rpl)#' level, when it should be at the '(config)#' level, causing the 'show commit changes diff' to fail.

fatal: [iosxr_router]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "configured by iosxr_config",
            "config": null,
            "disable_default_comment": false,
            "exclusive": false,
            "force": false,
            "label": null,
            "lines": [
                "route-policy POLICY1($SID)",
                "set community COMMUNITY1",
                "set label-index $SID",
                "end-policy",
                "route-policy POLICY2",
                "pass",
                "end-policy"
            ],
            "match": "none",
            "parents": null,
            "provider": null,
            "replace": "line",
            "src": null
        }
    },
    "msg": "show commit changes diff\r\n\r                                             ^\r\n% Invalid input detected at '^' marker.\r\nRP/0/RSP0/CPU0:iosxr_router(config-rpl)#"
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
iosxr_router               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```paste below
ansible-playbook [core 2.11.5] 
  config file = /home/user/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/scripts/py/junos-pyez/venv/lib64/python3.6/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/scripts/py/junos-pyez/venv/bin/ansible-playbook
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 2.11.2
  libyaml = True
Using /home/user/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/user/scripts/py/junos-pyez/venv/bin/scripts/hosts.save as it did not pass its verify_file() method
script declined parsing /home/user/scripts/py/junos-pyez/venv/bin/scripts/hosts.save as it did not pass its verify_file() method
auto declined parsing /home/user/scripts/py/junos-pyez/venv/bin/scripts/hosts.save as it did not pass its verify_file() method
yaml declined parsing /home/user/scripts/py/junos-pyez/venv/bin/scripts/hosts.save as it did not pass its verify_file() method
Parsed /home/user/scripts/py/junos-pyez/venv/bin/scripts/hosts.save inventory source with ini plugin
Loading collection ansible.netcommon from /home/user/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection cisco.iosxr from /home/user/.ansible/collections/ansible_collections/cisco/iosxr
Loading callback plugin default of type stdout, v2.0 from /home/user/scripts/py/junos-pyez/venv/lib64/python3.6/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: multiple_policy_test.yml *****************************************************************************************************************************************************************************************************
Positional arguments: /home/user/scripts/py/junos-pyez/venv/bin/scripts/multiple_policy_test.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/user/scripts/py/junos-pyez/venv/bin/scripts/hosts.save',)
subset: iosxr_router
forks: 5
1 plays in /home/user/scripts/py/junos-pyez/venv/bin/scripts/multiple_policy_test.yml

PLAY [Manipulate the configuration of Junos devices] ***********************************************************************************************************************************************************************************
META: ran handlers

TASK [policy] **************************************************************************************************************************************************************************************************************************
task path: /home/user/scripts/py/junos-pyez/venv/bin/scripts/multiple_policy_test.yml:12
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.iosxr to cisco.iosxr.iosxr
redirecting (type: cliconf) ansible.builtin.iosxr to cisco.iosxr.iosxr
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<iosxr_router> attempting to start connection
<iosxr_router> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /home/user/scripts/py/junos-pyez/venv/bin/ansible-connection
<iosxr_router> local domain socket does not exist, starting it
<iosxr_router> control socket path is /home/user/.ansible/pc/f8ff5acc78
<iosxr_router> redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
<iosxr_router> Loading collection ansible.netcommon from /home/user/.ansible/collections/ansible_collections/ansible/netcommon
<iosxr_router> redirecting (type: terminal) ansible.builtin.iosxr to cisco.iosxr.iosxr
<iosxr_router> Loading collection cisco.iosxr from /home/user/.ansible/collections/ansible_collections/cisco/iosxr
<iosxr_router> redirecting (type: cliconf) ansible.builtin.iosxr to cisco.iosxr.iosxr
<iosxr_router> local domain socket listeners started successfully
<iosxr_router> loaded cliconf plugin ansible_collections.cisco.iosxr.plugins.cliconf.iosxr from path /home/user/.ansible/collections/ansible_collections/cisco/iosxr/plugins/cliconf/iosxr.py for network_os iosxr
<iosxr_router> ssh type is set to paramiko
<iosxr_router> 
<iosxr_router> local domain socket path is /home/user/.ansible/pc/f8ff5acc78
<iosxr_router> Using network group action iosxr for iosxr_config
<iosxr_router> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<iosxr_router> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<iosxr_router> ESTABLISH LOCAL CONNECTION FOR USER: user
<iosxr_router> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-local-27436rg0e1vih `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-local-27436rg0e1vih/ansible-tmp-1653677000.836352-27449-173276530790200 `" && echo ansible-tmp-1653677000.836352-27449-173276530790200="` echo /home/user/.ansible/tmp/ansible-local-27436rg0e1vih/ansible-tmp-1653677000.836352-27449-173276530790200 `" ) && sleep 0'
Using module file /home/user/.ansible/collections/ansible_collections/cisco/iosxr/plugins/modules/iosxr_config.py
<iosxr_router> PUT /home/user/.ansible/tmp/ansible-local-27436rg0e1vih/tmp456i72u_ TO /home/user/.ansible/tmp/ansible-local-27436rg0e1vih/ansible-tmp-1653677000.836352-27449-173276530790200/AnsiballZ_iosxr_config.py
<iosxr_router> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-local-27436rg0e1vih/ansible-tmp-1653677000.836352-27449-173276530790200/ /home/user/.ansible/tmp/ansible-local-27436rg0e1vih/ansible-tmp-1653677000.836352-27449-173276530790200/AnsiballZ_iosxr_config.py && sleep 0'
<iosxr_router> EXEC /bin/sh -c '/home/user/scripts/py/junos-pyez/venv/bin/python3 /home/user/.ansible/tmp/ansible-local-27436rg0e1vih/ansible-tmp-1653677000.836352-27449-173276530790200/AnsiballZ_iosxr_config.py && sleep 0'
<iosxr_router> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-local-27436rg0e1vih/ansible-tmp-1653677000.836352-27449-173276530790200/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_iosxr_config_payload_qf8omu2g/ansible_iosxr_config_payload.zip/ansible_collections/cisco/iosxr/plugins/module_utils/network/iosxr/iosxr.py", line 573, in load_config
    label=label,
  File "/tmp/ansible_iosxr_config_payload_qf8omu2g/ansible_iosxr_config_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [iosxr_router]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "configured by iosxr_config",
            "config": null,
            "disable_default_comment": false,
            "exclusive": false,
            "force": false,
            "label": null,
            "lines": [
                "route-policy POLICY1($SID)",
                "set community COMMUNITY1",
                "set label-index $SID",
                "end-policy",
                "route-policy POLICY2",
                "pass",
                "end-policy"
            ],
            "match": "none",
            "parents": null,
            "provider": null,
            "replace": "line",
            "src": null
        }
    },
    "msg": "show commit changes diff\r\n\r                                             ^\r\n% Invalid input detected at '^' marker.\r\nRP/0/RSP0/CPU0:iosxr_router(config-rpl)#"
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
iosxr_router               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by ashwini-mhatre** [comment]
Please Use parents key along with lines while using iosxr_config module. check documentation for more details https://docs.ansible.com/ansible/latest/collections/cisco/iosxr/iosxr_config_module.html  
```
- name: configure policy1
  cisco.iosxr.iosxr_config:
    lines:
    - set community COMMUNITY1
    - set label-index $SID
    - end-policy
    parents: route-policy POLICY1($SID)

- name: configure policy2
  cisco.iosxr.iosxr_config:
    lines:
    - pass
    - end-policy
    parents: route-policy POLICY2
```

**Comment by PapaRobba** [comment]
Splitting the policies into individual tasks works even without parents, but that's not the issue. The issue is that we can configure multiple policies in the same task using ```iosxr_config: src:``` but not natively with ```iosxr_config: lines:``` unless we join the array into a single string. This is demonstrated below.

This playbook works using a file as the source:

```
- name: IOSXR Test with src
  hosts:
    - all
  vars:
    - mylist: ['community-set COMMUNITY1','123:456','end-set','route-policy POLICY1($SID)','set community COMMUNITY1','set label-index $SID','end-policy','route-policy POLICY2','pass','end-policy']
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Do stuff with policies
      block:
        - copy:
            content: "{{ mylist | join('\n') }}"
            dest: /tmp/config.file
            
        - iosxr_config:
            src: /tmp/config.file
            match: none
      always:
        - file:
            path: /tmp/config.file
            state: absent
```
```
ansible-playbook -i ./hosts.save -l iosxr_router iosxrtestwithsrc.yml -vvvv

changed: [iosxr_router] => {
    "changed": true,
    "commands": [
        "community-set COMMUNITY1",
        "123:456",
        "end-set",
        "route-policy POLICY1($SID)",
        "set community COMMUNITY1",
        "set label-index $SID",
        "end-policy",
        "route-policy POLICY2",
        "pass",
        "end-policy"
    ],
    "diff": {
        "prepared": "Building configuration...\n!! IOS XR Configuration 6.1.4\n   !\n   community-set COMMUNITY1\n-    123:456\n+    123:456\n   end-set\n   route-policy POLICY1($SID)\n-    set community COMMUNITY1\n-    set label-index $SID\n+    set community COMMUNITY1\n+    set label-index $SID\n   end-policy\n   route-policy POLICY2\n-    pass\n+    pass\n   end-policy\nend"
    },
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "configured by iosxr_config",
            "config": null,
            "disable_default_comment": false,
            "exclusive": false,
            "force": false,
            "label": null,
            "lines": null,
            "match": "none",
            "parents": null,
            "provider": null,
            "replace": "line",
            "src": "community-set COMMUNITY1\n123:456\nend-set\nroute-policy POLICY1($SID)\nset community COMMUNITY1\nset label-index $SID\nend-policy\nroute-policy POLICY2\npass\nend-policy"
        }
    }
}
```

This playbook with the same configs as 'lines' doesn't work:

```
- name: IOSXR Test with lines
  hosts:
    - all
  vars:
    - mylist: ['community-set COMMUNITY1','123:456','end-set','route-policy POLICY1($SID)','set community COMMUNITY1','set label-index $SID','end-policy','route-policy POLICY2','pass','end-policy']
  connection: network_cli
  gather_facts: no
  tasks:
    - name: policy #1
      iosxr_config:
        lines: "{{ mylist }}"
        match: none
```

```
ansible-playbook -i ./hosts.save -l iosxr_router iosxrtestwithlines.yml -vvvv

fatal: [iosxr_router]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "configured by iosxr_config",
            "config": null,
            "disable_default_comment": false,
            "exclusive": false,
            "force": false,
            "label": null,
            "lines": [
                "community-set COMMUNITY1",
                "123:456",
                "end-set",
                "route-policy POLICY1($SID)",
                "set community COMMUNITY1",
                "set label-index $SID",
                "end-policy",
                "route-policy POLICY2",
                "pass",
                "end-policy"
            ],
            "match": "none",
            "parents": null,
            "provider": null,
            "replace": "line",
            "src": null
        }
    },
    "msg": "show commit changes diff\r\n\r                                             ^\r\n% Invalid input detected at '^' marker.\r\nRP/0/RSP0/CPU0:iosxr_router(config-rpl)#"
}
```

This happens because duplicate lines, ```end-policy``` in this case, are removed. This leaves us stuck at the ```iosxr_router(config-rpl)#``` prompt where the ```show commit changes diff``` command isn't valid. If the second ```end-policy``` would have been executed, we would be at the ```iosxr_router(config)#``` prompt where ```show commit changes diff``` works.

To further demonstrate, if we take the same configs from the failed playbook and convert them to a ```\n``` joined string, it works. We no longer have a duplicate ```end-policy``` because they're all on one line.

```
- name: IOSXR Test with lines joined
  hosts:
    - all
  vars:
    - mylist: ['community-set COMMUNITY1','123:456','end-set','route-policy POLICY1($SID)','set community COMMUNITY1','set label-index $SID','end-policy','route-policy POLICY2','pass','end-policy']
  connection: network_cli
  gather_facts: no
  tasks:
    - set_fact:
        mylist: "{{ '\n'.join(mylist) }}"
    - name: policy #1
      iosxr_config:
        lines: "{{ mylist }}"
        match: none
```
```
ansible-playbook -i ./hosts.save -l iosxr_router iosxrtestwithlinesjoined.yml -vvvv

ok: [iosxr_router] => {
    "ansible_facts": {
        "mylist": "community-set COMMUNITY1\n123:456\nend-set\nroute-policy POLICY1($SID)\nset community COMMUNITY1\nset label-index $SID\nend-policy\nroute-policy POLICY2\npass\nend-policy"
    },
    "changed": false
}

changed: [iosxr_router] => {
    "changed": true,
    "commands": [
        "community-set COMMUNITY1",
        "123:456",
        "end-set",
        "route-policy POLICY1($SID)",
        "set community COMMUNITY1",
        "set label-index $SID",
        "end-policy",
        "route-policy POLICY2",
        "pass",
        "end-policy"
    ],
    "diff": {
        "prepared": "Building configuration...\n!! IOS XR Configuration 6.1.4\n   !\n   community-set COMMUNITY1\n-    123:456\n+    123:456\n   end-set\n   route-policy POLICY1($SID)\n-    set community COMMUNITY1\n-    set label-index $SID\n+    set community COMMUNITY1\n+    set label-index $SID\n   end-policy\n   route-policy POLICY2\n-    pass\n+    pass\n   end-policy\nend"
    },
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "configured by iosxr_config",
            "config": null,
            "disable_default_comment": false,
            "exclusive": false,
            "force": false,
            "label": null,
            "lines": [
                "community-set COMMUNITY1\n123:456\nend-set\nroute-policy POLICY1($SID)\nset community COMMUNITY1\nset label-index $SID\nend-policy\nroute-policy POLICY2\npass\nend-policy"
            ],
            "match": "none",
            "parents": null,
            "provider": null,
            "replace": "line",
            "src": null
        }
    }
}
```

```iosxr_config: src:``` and ```iosxr_config: lines:``` are parsed differently, and ```iosxr_config: lines:``` breaks because duplicates lines are removed.

You can see where it's happening in these modules:
[ansible_collections.cisco.iosxr.plugins.modules.iosxr_config](https://github.com/ansible-collections/cisco.iosxr/blob/main/plugins/modules/iosxr_config.py)
```
def get_candidate(module):
    candidate = ""
    if module.params["src"]:
        candidate = module.params["src"]    <--src: is passed without modification
    elif module.params["lines"]:
        candidate_obj = NetworkConfig(indent=1, comment_tokens=["!"])
        parents = module.params["parents"] or list()
        candidate_obj.add(module.params["lines"], parents=parents)    <--lines: gets passed to NetworkConfig
        candidate = dumps(candidate_obj, "raw")
    return candidate
```
And:
[ansible_collections.ansible.netcommon.plugins.module_utils.network.common.config](https://github.com/ansible-collections/ansible.netcommon/blob/main/plugins/module_utils/network/common/config.py)
```
class NetworkConfig(object):
    def add(self, lines, parents=None):
        ancestors = list()
        offset = 0
        obj = None

        # global config command
        if not parents:
            for line in lines:
                # handle ignore lines
                if ignore_line(line, self.comment_tokens):
                    continue

                item = ConfigLine(line)
                item.raw = line
                if item not in self.items:    <--NetworkConfig ignores duplicate lines
                    self.items.append(item)
```
