### ISSUE TITLE
Commit confirmed doesn't work with replace: config

### ISSUE THREAD

**Issue by JaakkoRautanen** [ansible-collections/cisco.iosxr#249]
##### SUMMARY

Issue [199](https://github.com/ansible-collections/cisco.iosxr/issues/199) describes commit confirmed feature. It has been developed and released. It works well without replace: config - parameter but not with that.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu-user/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ubuntu-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/ubuntu-user/.ansible/collections/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 3.0.0  
```

##### CONFIGURATION

```paste below
-empty-
```

##### OS / ENVIRONMENT

```yaml
Tue May 31 11:39:18.569 UTC
Cisco IOS XR Software, Version 7.4.1
Copyright (c) 2013-2021 by Cisco Systems, Inc.

Build Information:
 Built By     : ingunawa
 Built On     : Wed Aug  4 04:23:45 PDT 2021
 Built Host   : iox-ucs-013
 Workspace    : /auto/srcarchive17/prod/7.4.1/ncs5500/ws
 Version      : 7.4.1
 Location     : /opt/cisco/XR/packages/
 Label        : 7.4.1

cisco NCS-5500 () processor
System uptime is 3 weeks 23 hours 2 minutes
```

##### STEPS TO REPRODUCE

Run the playbook below. If you run without replace: config, it works.

```yaml
---
- name:  load a config from disk and replace the current config
  hosts: xr-routers
  gather_facts: no
  
  vars:
  - path_configs: "configs"

  tasks:
  - name: First commit with confirmed
    vars:
      ansible_iosxr_commit_confirmed: true
      ansible_iosxr_commit_confirmed_timeout: 30
    cisco.iosxr.iosxr_config:
      src: "{{path_configs}}/{{inventory_hostname}}-config.cfg"
      replace: config
      backup: yes
```

##### EXPECTED RESULTS

Commit confirmed should work same way with and without replace: config. This means rollback should happen if no new commit is made during 30 seconds.

##### ACTUAL RESULTS

Rollback didn't happen and configuration become permanent.

```paste below

```
