### ISSUE TITLE
How to make permanent changes with commit_confirmed?

### ISSUE THREAD

**Issue by JaakkoRautanen** [ansible-collections/cisco.iosxr#260]
##### SUMMARY

Commit confirmed feature works with IOS XR devices (but not with replace: config as seen here: [249](https://github.com/ansible-collections/cisco.iosxr/issues/249)) so that rollback happens. But this is not all. So we have to apply _SECOND_ commit during _SAME_ SSH session before commit confirmed timeout has been expired. This doesn't work. At least I haven't find way to do it. We cannot use second task in playbook since it creates _new_ ssh session. See below. When I SSH to IOS XR device, make change, commit confirmed and try to exit configuration mode before rollback has happened it says: 
```paste below
You are exiting after a 'commit confirm' with an active rollback session.  If you exit the configuration awaiting confirmation will not be confirmed and the router will immediately rollback to the previous configuration.
Do you wish to exit? [no]:
```

How can we handle this? This feature is supposed to add safety to automation. If changes you apply breaks SSH connection second commit doesn't go through and rollback happens. So second commit needs to happen in the middle of commit_confirm_timeout period.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/user/.ansible/collections/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 3.1.0  
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
Thu Jul  7 16:00:10.220 EEST
Cisco IOS XR Software, Version 7.6.1
Copyright (c) 2013-2022 by Cisco Systems, Inc.

Build Information:
 Built By     : ingunawa
 Built On     : Sat Mar 26 20:01:52 PDT 2022
 Built Host   : iox-ucs-047
 Workspace    : /auto/srcarchive17/prod/7.6.1/ncs5500/ws
 Version      : 7.6.1
 Location     : /opt/cisco/XR/packages/
 Label        : 7.6.1

cisco NCS-5500 () processor
System uptime is 2 days 23 hours 45 minutes
```

##### STEPS TO REPRODUCE

```yaml
---
- name:  load a config from disk and replace the current config
  hosts: iosxr-router1
  gather_facts: no

  tasks:
  - name: Commit with confirmed
    vars:
      ansible_iosxr_commit_confirmed: true
      ansible_iosxr_commit_confirmed_timeout: 60
    cisco.iosxr.iosxr_config:
      src: "configs/{{inventory_hostname}}-config.cfg"
      replace: config
      backup: yes
```

##### EXPECTED RESULTS

Configuration changes should be permanent on IOS XR router after second commit.

##### ACTUAL RESULTS

Second commit doesn't happen.

```paste below

```
