### ISSUE TITLE
iosxr_facts bgp_global subset ignores neighbor descriptions with comments

### ISSUE THREAD

**Issue by larryj0nes** [ansible-collections/cisco.iosxr#305]
##### SUMMARY
When gathering facts with iosxr.iosxr_facts, the bgp_global network resoruce subset does not return neighbor descriptions if the bgp neighbor description in the running-config contains spaces.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iosxr_facts

##### ANSIBLE VERSION

```
ansible [core 2.13.2]

```

##### COLLECTION VERSION

```
# /usr/local/lib/python3.9/site-packages/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 4.0.3  

# /usr/local/spe-dev/ansible/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 4.0.3 
```

##### CONFIGURATION

```
no output

```

##### OS / ENVIRONMENT
FreeBSD 12.2-RELEASE-p7

##### STEPS TO REPRODUCE

```
- name: XR Facts
  connection: local
  hosts: remotehostname
  gather_facts: false
  tasks:
    - name: gather facts
      cisco.iosxr.iosxr_facts:
        gather_subset:
          - '!all'
        gather_network_resources:
          - bgp_neighbor_address_family
          - bgp_address_family
          - bgp_global


```

##### ACTUAL RESULTS
...brief example of output
                            {
                                "neighbor_address": "x.x.x.x",
                                "remote_as": 714
                            },
                            {
                                "description": "MICROSOFT-CH1",
                                "neighbor_address": "x.x.x.x",
                                "remote_as": 8075
                            },

The description field is not included in the returned data when the description contains a space.
