### ISSUE TITLE
When executing config changes to IOSXR device, the resulting commit record on the device does not have the label

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#313]
##### SUMMARY

cisco.iosxr.iosxr_bgp_neighbor_address_family

##### ANSIBLE VERSION

```paste below

(ansible213_venv) REDACTED@REDACTED-dev:~/REDACTED/gitlab/sips/ansible-playbooks/REDACTED$ ansible --version
ansible [core 2.13.4]
  config file = /media/REDACTED/gitlab/sips/ansible-playbooks/REDACTED/ansible.cfg
  configured module search path = ['/home/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/REDACTED/ansible213_venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/REDACTED/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/REDACTED/ansible213_venv/bin/ansible
  python version = 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below

(ansible213_venv) REDACTED@REDACTED-dev:~/REDACTED/gitlab/sips/ansible-playbooks/REDACTED$ ansible-galaxy collection list cisco.iosxr

# /home/REDACTED/ansible213_venv/lib/python3.10/site-packages/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 4.0.2

```

##### CONFIGURATION

```paste below

(ansible213_venv) REDACTED@REDACTED-dev:~/REDACTED/gitlab/sips/ansible-playbooks/REDACTED$ ansible-config dump --only-changed
DEFAULT_LOG_PATH(/media/REDACTED/gitlab/sips/ansible-playbooks/REDACTED/ansible.cfg) = /home/REDACTED/REDACTED/ansible_job_logs/ansible_log
(ansible213_venv) REDACTED@REDACTED-dev:~/REDACTED/gitlab/sips/ansible-playbooks/REDACTED$

```

##### OS / ENVIRONMENT

RP/0/RSP1/CPU0:ASR9K-01#show version
Tue Nov 22 10:50:25.646 GMT

Cisco IOS XR Software, Version 6.5.3[Default]
Copyright (c) 2019 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 10.65(c) 1994-2014 by Cisco Systems,  Inc.

ASR9K-01 uptime is 1 year, 20 weeks, 4 days, 20 hours, 59 minutes
System image file is "disk0:asr9k-os-mbi-6.5.3/0x100305/mbiasr9k-rsp3.vm"

cisco ASR9K Series (Intel 686 F6M14S4) processor with 16777216K bytes of memory.
Intel 686 F6M14S4 processor at 1904MHz, Revision 2.174
ASR-9010 8 Line Card Slot Chassis with V3 AC PEM
RP/0/RP0/CPU0:NCS55A1-01#show version
Tue Nov 22 16:50:26.158 GMT
Cisco IOS XR Software, Version 7.2.2
Copyright (c) 2013-2021 by Cisco Systems, Inc.

Build Information:
 Built By     : ingunawa
 Built On     : Mon Jan 25 21:52:54 PST 2021
 Built Host   : iox-ucs-013
 Workspace    : /auto/srcarchive15/prod/7.2.2/ncs5500/ws
 Version      : 7.2.2
 Location     : /opt/cisco/XR/packages/
 Label        : 7.2.2

cisco NCS-5500 () processor

##### STEPS TO REPRODUCE

```yaml

---
- set_fact:
number_of_commit_labels: "{{ number_of_commit_labels | int + 1 }}"

- name: Configure BGP Neighbor Address Family
vars:
disable_default_comment: true
ansible_iosxr_commit_label: "CR{{ CR_number }}_bgp_{{ number_of_commit_labels }}"
cisco.iosxr.iosxr_bgp_neighbor_address_family:
config: "{{ network_service_config['bgp_neighbor_address_family'] }}"
state: "{{ network_service_config['state'] }}"
register: bgp_neighbor_address_family_config

```

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above →

After successful commit, the commit history on the IOSXR device will show the custom commit label instead of the default commit id. Example:

RP/0/RP0/CPU0:NCS55A1-01#show configuration commit list | i CR
Tue Nov 22 16:55:09.145 GMT
9    CR000000117_int_1     useridx  vty0:node0_RP0_CPU  CLI         Tue Nov 15 16:31:16 2022

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra
verbosity (-vvvv) →

Example of current commit that fails to apply the commit label:

RP/0/RP0/CPU0:NCS55A1-01#show configuration commit list
Tue Nov 22 16:56:32.390 GMT
SNo. Label/ID              User      Line                Client      Time Stamp
~~~~ ~~~~~~~~              ~~~~      ~~~~                ~~~~~~      ~~~~~~~~~~
1    1000084655            REDACTED  vty1:node0_RP0_CPU  CLI         Thu Nov 17 15:01:05 2022

<!--- Paste verbatim command output between quotes -->
```paste below

```
