### ISSUE TITLE
Resource module cisco.iosxr.iosxr bgp_neighbor_address_family  is not setting soft_reconfiguration inbound always even when provided on inventory and successful execution of the playbook

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#325]
##### SUMMARY
Resource module cisco.iosxr.iosxr bgp_neighbor_address_family  is not setting soft_reconfiguration inbound always even when provided on inventory and successful execution of the playbook, in both default and vrf contexts.

Currently, under neighbors dictionary, the soft_reconfigurationinbound dictionary has keys always and set available. When both are set to true, the resulting configuration on an iosxr device should reflect

neighbor X.X.2.2
  remote-as 65537
  description AdiTest_IPv4_Global
  address-family ipv4 unicast
   route-policy SB-IPV4-NO-DEFAULT-IN in
   maximum-prefix 2000 75 restart 5
   route-policy SB-IPV4-DEFAULT-OUT out
   soft-reconfiguration inbound always
  !
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.iosxr.iosxr_bgp_neighbor_address_family

##### ANSIBLE VERSION

```paste below
[REDACTED@YETI_RHEL8 yeti-modular-network-services]$ ansible --version
ansible [core 2.12.6]
  config file = /home/REDACTED/.ansible.cfg
  configured module search path = ['/home/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/REDACTED/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.2
  libyaml = True
[REDACTED@YETI_RHEL8 yeti-modular-network-services]$
```

##### COLLECTION VERSION

```
[REDACTED@YETI_RHEL8 yeti-modular-network-services]$ ansible-galaxy collection list cisco.iosxr
# /home/REDACTED/.ansible/collections/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 4.0.3
[REDACTED@YETI_RHEL8 yeti-modular-network-services]$
```

##### CONFIGURATION

```
[REDACTED@YETI_RHEL8 yeti-modular-network-services]$ ansible-config dump --only-changed
DEFAULT_EXECUTABLE(/home/REDACTED/.ansible.cfg) = /bin/bash
DEFAULT_JINJA2_EXTENSIONS(/home/REDACTED/.ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_LOCAL_TMP(/home/REDACTED/.ansible.cfg) = /home/REDACTED/.ansible/tmp/ansible-local-1527557zldutxcr
DEFAULT_LOG_PATH(/home/REDACTED/.ansible.cfg) = /home/REDACTED/.ansible/log
DEFAULT_REMOTE_PORT(/home/REDACTED/.ansible.cfg) = 22
DEFAULT_STDOUT_CALLBACK(/home/REDACTED/.ansible.cfg) = skippy
DEFAULT_TIMEOUT(/home/REDACTED/.ansible.cfg) = 120
DEFAULT_TRANSPORT(/home/REDACTED/.ansible.cfg) = smart
DEPRECATION_WARNINGS(/home/REDACTED/.ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/REDACTED/.ansible.cfg) = True
GALAXY_IGNORE_CERTS(/home/REDACTED/.ansible.cfg) = True
GALAXY_SERVER_LIST(/home/REDACTED/.ansible.cfg) = ['published_repo', 'rh-certified_repo', 'release_galaxy']
HOST_KEY_CHECKING(/home/REDACTED/.ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/home/REDACTED/.ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/home/REDACTED/.ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/home/REDACTED/.ansible.cfg) = 120
RETRY_FILES_ENABLED(/home/REDACTED/.ansible.cfg) = False
[REDACTED@YETI_RHEL8 yeti-modular-network-services]$

```

##### OS / ENVIRONMENT

Cisco IOS XR Software, Version 6.5.3
Cisco IOS XR Software, Version 7.2.2

    - "ASR-9010"
    - "ASR 9922"
    - "cisco 8201-32FH"
    - "cisco NCS-5500"

---
# ansible-playbook -i staging/bgp/neighbor_add/hosts_sandbox.yml implementation.yml -l ASR9K-01 -e @/opt/yeti/yeti_secrets.yml -e @~/local_secrets.yml --ask-vault-pass

yeti_network_services:
  #### neighbor add
  - configs:
      - bgp_neighbor_address_family:
          as_number: "65137"
          neighbors:
            - neighbor_address: X.X.2.2
              address_family:
                - afi: "ipv4"
                  safi: "unicast"
                  default_originate:
                    set: true
                  maximum_prefix:
                    max_limit: 2000
                    restart: 5
                    threshold_value: 75
                    warning_only: false
                  next_hop_self:
                    set: true
                  route_policy:
                    inbound: "SB-IPV4-NO-DEFAULT-IN"
                    outbound: "SB-IPV4-DEFAULT-OUT"
                  send_community_ebgp:
                    set: true
                  remove_private_AS:
                    set: true
                  soft_reconfiguration:
                    inbound:
                      always: true
                      set: true
          vrfs:
            - vrf: RGW
              neighbors:
                - neighbor_address: X.X.2.4
                  address_family:
                    - afi: "ipv4"
                      safi: "unicast"
                      route_policy:
                        inbound: "BLOCK-ALL"
                        outbound: "BLOCKALL"                  
                      maximum_prefix:
                        max_limit: 2000
                        restart: 5
                        threshold_value: 75
                        warning_only: false                      
                      default_originate:
                        set: true
                      next_hop_self:
                        set: true
                      send_community_ebgp:
                        set: true                        
                      remove_private_AS:
                        set: true
                      soft_reconfiguration:
                        inbound:
                          always: true
                          inheritance_disable: false
                          set: true
        state: merged

---
- name: Configure BGP NBR
  cisco.iosxr.iosxr_bgp_neighbor_address_family:
    config: "{{ yeti_network_services['configs']['bgp_neighbor_address_family'] }}"
    state: "{{ yeti_network_services['configs']['state'] }}"
  vars:
    disable_default_comment: true
  register: bgp_neighbor_address_family_config

```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS

The completed configuration on host device should reflect :


neighbor X.X.2.2
  remote-as 65537
  description AdiTest_IPv4_Global
  address-family ipv4 unicast
   route-policy SB-IPV4-NO-DEFAULT-IN in
   maximum-prefix 2000 75 restart 5
   route-policy SB-IPV4-DEFAULT-OUT out
   soft-reconfiguration inbound always
  !

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra
verbosity (-vvvv) -->
RP/0/RSP1/CPU0:ASR9K-01#show run router bgp | begin "neighbor X.X.2.2"
neighbor X.X.2.2
  remote-as 65537
  shutdown
  description AdiTest_IPv4_Global
  address-family ipv4 unicast
   send-community-ebgp
   route-policy SB-IPV4-NO-DEFAULT-IN in
   maximum-prefix 2000 75 restart 5
   route-policy SB-IPV4-DEFAULT-OUT out
   default-originate
   next-hop-self
   remove-private-AS
   soft-reconfiguration inbound
  !
RP/0/RSP1/CPU0:ASR9K-01#show run router bgp | begin "neighbor X.X.2.4"
  neighbor X.X.2.4
   remote-as 65538
   use neighbor-group SB-IPV4-GROUP
   shutdown
   description AdiTestVRF_IPv4_RGW
   address-family ipv4 unicast
    send-community-ebgp
    route-policy BLOCK-ALL in
    maximum-prefix 2000 75 restart 5
    route-policy BLOCKALL out
    default-originate
    next-hop-self
    remove-private-AS
    soft-reconfiguration inbound inheritance-disable
   !
<!--- Paste verbatim command output between quotes -->
```paste below



```

**Comment by ashwini-mhatre** [comment]
@digitalfiend64 
```
yeti_network_services:
  #### neighbor add
  - configs:
      - bgp_neighbor_address_family:
          as_number: "65137"
          neighbors:
            - neighbor_address: X.X.2.2
              address_family:
                - afi: "ipv4"
                  safi: "unicast"
                  default_originate:
                    set: true
                  maximum_prefix:
                    max_limit: 2000
                    restart: 5
                    threshold_value: 75
                    warning_only: false
                  next_hop_self:
                    set: true
                  route_policy:
                    inbound: "SB-IPV4-NO-DEFAULT-IN"
                    outbound: "SB-IPV4-DEFAULT-OUT"
                  send_community_ebgp:
                    set: true
                  remove_private_AS:
                    set: true
                  soft_reconfiguration:
                    inbound:
                      always: true
                      
          vrfs:
            - vrf: RGW
              neighbors:
                - neighbor_address: X.X.2.4
                  address_family:
                    - afi: "ipv4"
                      safi: "unicast"
                      route_policy:
                        inbound: "BLOCK-ALL"
                        outbound: "BLOCKALL"                  
                      maximum_prefix:
                        max_limit: 2000
                        restart: 5
                        threshold_value: 75
                        warning_only: false                      
                      default_originate:
                        set: true
                      next_hop_self:
                        set: true
                      send_community_ebgp:
                        set: true                        
                      remove_private_AS:
                        set: true
                      soft_reconfiguration:
                        inbound:
                          always: true
        state: merged


```

you can use either set or always or inheritance_disable
