### ISSUE TITLE
l2_interfaces resource information missing on High Bandwidth Interfaces 

### ISSUE THREAD

**Issue by tweippert** [ansible-collections/cisco.iosxr#366]
##### SUMMARY

Using l2_interfaces in gather_network_resources always empty on ASR 9903. Think this is due to the fact, 
that in the l2_interfaces fact gathering only Interfaces recognized which are starting with "gi" (lower), and
no Interfaces > GigabitEthernet are recognized.

PR will follow.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_l2_interfaces & gather_network_resources for l2_interfaces

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0]
  config file = /home/weipperttadm/Develop/iosxr_tests/ansible.cfg
  configured module search path = ['/home/weipperttadm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/weipperttadm/pyenv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/weipperttadm/ansible-aap/collections:/home/weipperttadm/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/weipperttadm/pyenv/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection  Version
----------- -------
cisco.iosxr 5.0.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  connection: network_cli
  gather_facts: no

  tasks:

  - name: Gather Facts
    cisco.iosxr.iosxr_facts:
      gather_subset:
        - all
      gather_network_resources:
        - interfaces
        - l2_interfaces
      available_network_resources: true
```

##### EXPECTED RESULTS

Get all Interfaces on the system (may empty)

```
            "l2_interfaces": [
                {
                    "name": "HundredGigE0/0/0/0"
                },
                [...]
                {
                    "name": "TenGigEt0/0/0/16"
                },
                [...]
```

##### ACTUAL RESULTS

No  l2_interfaces resource information on ASR 9903
