### ISSUE TITLE
Missing Bundle(-Ether) Interfaces in network_resources

### ISSUE THREAD

**Issue by tweippert** [ansible-collections/cisco.iosxr#369]
##### SUMMARY
Bundle-Ether interfaces are not found by the network resources facts, at least on ASR-9903 IOS-XR 7.5.2.

PR to discuss will follow.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

e.g.: iosxr_l3_interfaces

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0]
  config file = /home/weipperttadm/Develop/iosxr_tests/ansible.cfg
  configured module search path = ['/home/weipperttadm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/weipperttadm/pyenv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/weipperttadm/ansible-aap/collections:/home/weipperttadm/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/weipperttadm/pyenv/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection  Version
----------- -------
cisco.iosxr 5.0.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  connection: network_cli
  gather_facts: no

  tasks:

  - name: Gather Facts
    cisco.iosxr.iosxr_facts:
      gather_subset:
        - all
      gather_network_resources:
        - interfaces
        - l2_interfaces
        - l3_interfaces
      available_network_resources: true
```

##### EXPECTED RESULTS

Find Bundle-EtherXX Interfaces

##### ACTUAL RESULTS

No Bundle-Ether Interfaces found in the resources
