### ISSUE TITLE
wait_for does not work with multiple conditions

### ISSUE THREAD

**Issue by hmntsharma** [ansible-collections/cisco.iosxr#373]
##### SUMMARY

The wait_for feature does not work with multiple conditions
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = /home/lab/github/ansible-cisco-segment-routing/ansible.cfg
  configured module search path = ['/home/lab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lab/vntdvops/lib/python3.10/site-packages/ansible
  ansible collection location = /home/lab/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lab/vntdvops/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/home/lab/vntdvops/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection  Version
----------- -------
cisco.iosxr 4.1.0

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/lab/ansible.cfg
DEFAULT_FORKS(/home/lab/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/lab/ansible.cfg) = ['/home/lab/inventory/hosts.ini']
DEFAULT_STDOUT_CALLBACK(/home/lab/ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/home/lab/ansible.cfg) = False
HOST_KEY_CHECKING(/home/lab/ansible.cfg) = False
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/lab/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/lab/ansible.cfg) = 120

```

##### OS / ENVIRONMENT

Ubuntu 22.04.2 LTS 
Cisco XRv9k

##### STEPS TO REPRODUCE

```yaml
- name: "TEST"
  hosts: PE1
  gather_facts: false
  vars:
    command_set_1:
    - show version
    - show users
  tasks:
  - name: run show version and check to see if output contains iosxr
    cisco.iosxr.iosxr_command:
      commands: 
      - "{{ item }}"
      wait_for: 
      - result[0] contains 'IOS-XR'
      - result[0] contains 'cisco'
    loop: "{{ command_set_1 }}"
    register: output

==========
RP/0/RP0/CPU0:PE1#show users
Thu Apr 13 12:28:47.411 UTC
   Line            User                 Service  Conns   Idle        Location
   vty0            cisco                ssh          0  00:00:39     192.168.18.100
*  vty1            cisco                ssh          0  00:00:04     192.168.18.100
RP/0/RP0/CPU0:PE1#

```

##### ACTUAL RESULTS

```paste below

TASK [run show version and check to see if output contains iosxr] ********************************************************************************************************************************************************
ok: [PE1] => (item=show version)
failed: [PE1] (item=show users) => changed=false
  ansible_loop_var: item
  failed_conditions:
  - result[0] contains 'IOS-XR'
  item: show users
  msg: One or more conditional statements have not been satisfied

PLAY RECAP ***************************************************************************************************************************************************************************************************************
PE1                        : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by ashwini-mhatre** [comment]
@hmntsharma in show users there is no word 'IOS-XR' that's why its failed

**Comment by ashwini-mhatre** [comment]
@hmntsharma  please check. the above task working fine

**Comment by hmntsharma** [comment]
Hi @ashwini-mhatre 

Here is the updated result.

Playbook
```
- name: "TEST"
  hosts: PE1
  gather_facts: false
  vars:
    command_set_1:
    - show version
    - show users
  tasks:
  - name: run show version and check to see if output contains iosxr
    cisco.iosxr.iosxr_command:
      commands:
      - "{{ item }}"
      wait_for:
      - result[0] contains 'IOS-XR'
      - result[1] contains 'cisco'
    loop: "{{ command_set_1 }}"
    register: output

```

Output
```
$ ansible-playbook temp.yml  -e ansible_user="cisco" -e ansible_password="cisco"

PLAY [TEST] ***********************************************************************************************************************************************************************************************************************

TASK [run show version and check to see if output contains iosxr] *****************************************************************************************************************************************************************
failed: [PE1] (item=show version) => changed=false
  ansible_loop_var: item
  item: show version
  module_stderr: unable to apply conditional to result
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
failed: [PE1] (item=show users) => changed=false
  ansible_loop_var: item
  item: show users
  module_stderr: unable to apply conditional to result
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error

PLAY RECAP ************************************************************************************************************************************************************************************************************************
PE1                        : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

CLI 

```
RP/0/RP0/CPU0:PE1#show version | i "IOS XR"
Fri May 19 14:06:44.665 UTC
Cisco IOS XR Software, Version 7.5.2
RP/0/RP0/CPU0:PE1#
RP/0/RP0/CPU0:PE1#show users | i cisco
Fri May 19 14:06:51.171 UTC
*  vty0            cisco                ssh          0  00:00:03     192.168.18.100
   vty1            cisco                ssh          0  00:02:03     192.168.18.100
   vty2            cisco                ssh          0  00:01:36     192.168.18.100
   vty3            cisco                ssh          0  00:00:56     192.168.18.100
RP/0/RP0/CPU0:PE1#
```
