### ISSUE TITLE
cisco.iosxr.iosxr_facts - Add cdp neighbours to ansible_net_neighbours facts.

### ISSUE THREAD

**Issue by jorgenspange** [ansible-collections/cisco.iosxr#440]
##### SUMMARY
Add cdp neighbours to ansible_net_neighbours facts.
It seems to only be lldp per now, as far as I can figure from the documentation:

```yaml
ansible_net_neighbors   | The list of LLDP neighbors from the remote device
dictionary              | Returned: when interfaces is configured
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cisco.iosxr.iosxr_facts

##### ADDITIONAL INFORMATION
Want to use this to set interface description. Here's how I am doing it with cisco.ios.ios:

Playbook:
```yaml
- name: configure_cisco.ios.ios | Gather interface facts.
  cisco.ios.ios_facts:
    gather_subset:
      - interfaces
  vars:
    ansible_command_timeout: 60

- name: configure_cisco.ios.ios | Set interface description.
  cisco.ios.ios_interfaces:
    config: "{{ interface_description_ios }}"
    state: merged
  when: interface_description_ios | length is gt(0)
  notify: Save ios.
```
Template
```j2
{% for interface_description_item in ansible_facts['net_neighbors'] | ansible.builtin.dict2items if interface_description_item['value'][0]['platform'] is defined %}
- name: {{ interface_description_item['key'] }}
  description: {{ interface_description_item['value'][0]['host'] }} via {{ interface_description_item['value'][0]['port'] }}
{% endfor %}
```
Vars
```yaml
interface_description_ios: "{{ lookup('ansible.builtin.template', 'interface_description_ios.j2') | ansible.builtin.from_yaml }}"
```

Would be nice to be able to do the same thing with iosxr.
