### ISSUE TITLE
cisco.iosxr.iosxr_interfaces gathered state not take in account

### ISSUE THREAD

**Issue by antoinekh** [ansible-collections/cisco.iosxr#451]
##### SUMMARY

The state gathered is not take in account with cisco.iosxr.iosxr_interfaces.
This works ok with others modules (ospf, bgp, static_route or others)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

The code:
```
- name: Gathered interfaces
  cisco.iosxr.iosxr_interfaces:
    state: gathered
  register: interfaces
  tags: [interfaces]
```

The result:
Configuration is well parsed but state is still merged
```
            },
                {
                    "enabled": false,
                    "name": "TwentyFiveGigE0/0/0/28"
                },
                {
                    "enabled": false,
                    "name": "TwentyFiveGigE0/0/0/29"
                },
                {
                    "enabled": false,
                    "name": "TwentyFiveGigE0/0/0/30"
                },
                {
                    "enabled": false,
                    "name": "TwentyFiveGigE0/0/0/31"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    }
}

MSG:

missing required arguments: name found in config
```
##### ANSIBLE VERSION

```paste below
09:23:17 antoine@pop-os ansible_backbone ±|main ✗|→ ansible --version
ansible 2.10.8
  config file = /home/antoine/ansible_backbone/ansible.cfg
  configured module search path = ['/home/antoine/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

##### COLLECTION VERSION

```paste below
09:22:50 antoine@pop-os ansible_backbone ±|main ✗|→ ansible-galaxy collection list cisco.iosxr

# /home/antoine/.ansible/collections/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 6.1.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 1.2.1  
09:23:17 antoine@pop-os ansible_backbone ±|main ✗|→ 
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/home/antoine/ansible_backbone/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/antoine/ansible_backbone/ansible.cfg) = ['/home/antoine/ansible_backbone/hosts']
DEFAULT_STDOUT_CALLBACK(/home/antoine/ansible_backbone/ansible.cfg) = debug
DEPRECATION_WARNINGS(/home/antoine/ansible_backbone/ansible.cfg) = False
HOST_KEY_CHECKING(/home/antoine/ansible_backbone/ansible.cfg) = False
INTERPRETER_PYTHON(/home/antoine/ansible_backbone/ansible.cfg) = /usr/bin/python3
SYSTEM_WARNINGS(/home/antoine/ansible_backbone/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Run os linux PopOs VM
Target iosxr Cisco devices

##### STEPS TO REPRODUCE

```yaml
   - hosts: all
     gather_facts: no
     strategy: free
     tasks:
      - name: Gathered interfaces
        cisco.iosxr.iosxr_interfaces:
          state: gathered
        register: interfaces
        tags: [interfaces]
```

##### EXPECTED RESULTS

state to gathered, and no error because config value is not set.

##### ACTUAL RESULTS

```paste below

```
