### ISSUE TITLE
iosxr_ping creates bad syntax for ping request

### ISSUE THREAD

**Issue by dalibordravecky** [ansible-collections/cisco.iosxr#545]
##### SUMMARY
When running iosxr_ping module, the module creates an ping request in the form of:
"ping vrf test-vrf **ipv4** 1.2.3.4" 
The problem is in "ipv4" keyword, because this syntax is not allowed on Cisco IOSXR router - as you can see from router CLI:
RP/0/RP0/CPU0:nkt-rt-xr2#ping vrf test-vrf ?
  WORD  Ping destination address or hostname
  <cr>  

There is no way how to remove the ipv4 keyword from module ( afi part in module is not required, but defualt is ipv4 )

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.iosxr 

##### ANSIBLE VERSION

```
2.17.9
```

##### COLLECTION VERSION

```
10.3.1
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```
 - name: I. PING
   cisco.iosxr.iosxr_ping:
     dest: "1.2.3.4"
     vrf: "test-vrf"
   tags: 
     - verify
     - ping
     - 
```

##### EXPECTED RESULTS

This is expected CLI command created by module:
ping vrf test-vrf 1.2.3.4

##### ACTUAL RESULTS

```paste below
This is actual CLI command created by module:
ping vrf test-vrf **ipv4** 1.2.3.4
```
