### ISSUE TITLE
IOS-XR Configuration: Fails to accurately report configuration failure during pseudo-atomic operation

### ISSUE THREAD

**Issue by nasedora** [ansible-collections/cisco.iosxr#92]
##### SUMMARY

Noticing an issue with the Ansible IOS-XR configuration module. It doesn't handle the following configuration failed message well : "% Failed to commit one or more configuration items during a pseudo-atomic operation. All changes made have been reverted. Please issue 'show configuration failed [inheritance]' from this session to view the errors". Even though no configuration was done, Ansible would report success. Running the same CLI lines on the device properly reports the error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_config

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nasedora/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
<no output>
```

##### OS / ENVIRONMENT

Vendor: Cisco
Type: Router
Model: Cisco ASR 9001
Version: 6.6.3

##### STEPS TO REPRODUCE

The only requirement for failure is that one of the lines in the .j2 template (as shown below) attempt to use a resource that doesn't exist on the device.

```
 # Start block for Cisco IOS-XR
    - block:
      - name: deploy configuration - Cisco IOS-XR
        check_mode: false
        iosxr_config:
          provider: "{{ cli }}"
          src: "{{ template_loc }}"
          comment: "Ansible Deploy Config Standards PB"
          match: "none"
        register: result_config

      - name: set fact containing changes made or to be made
        set_fact:
          cli_commands_run: "{{ cli_commands_run | default([]) + result_config.commands }}"
        when: result_config.commands is defined
      when: device_os == 'cisco-ios-xr'
  # End Block
```

##### EXPECTED RESULTS

Expect the module to return failure, not changed, and should show the following message in stdout: Failed to commit one or more configuration items during a pseudo-atomic operation. All changes made have been reverted. Please issue 'show configuration failed [inheritance]' from this session to view the errors.

##### ACTUAL RESULTS

Module returns success, and changed, and the commands field contains all of the configuration lines, none of which are actually applied (verified by checking the configuration on the actual device).

```
changed: [<hostname>] => {
    "changed": true,
    "commands": [
         <all commands from .j2 template>
    ],
    "invocation": {
        "module_args": {
            "admin": false,
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "comment": "Ansible Deploy Config Standards PB",
            "config": null,
            "exclusive": false,
            "force": false,
            "host": null,
            "label": null,
            "lines": null,
            "match": "none",
            "parents": null,
            "password": null,
            "port": null,
            "provider": {
                "host": "<hostname>",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": 120,
                "transport": "cli",
                "username": <username>
            },
            "replace": "line",
            "src": "<all commands from .j2 template>",
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    }
}
```
