### ISSUE TITLE
IOSXR: interface not getting configured with interface module when connection is netconf (DNM)

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-collections/cisco.iosxr#96]
##### SUMMARY

interface not getting configured with interface module when the connection is netconf 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_interface
##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /home/rothakur/playbooks/collections/cisco/iosxr/ansible.cfg
  configured module search path = ['/home/rothakur/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rothakur/ansible-collections/collections/ansible_collections/ansible-base/lib/ansible
  executable location = /home/rothakur/ansible-collections/collections/ansible_collections/ansible-base/bin/ansible
  python version = 3.7.9 (default, Sep 22 2020, 09:19:36) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]

```

##### CONFIGURATION

```paste below
[defaults]
INVENTORY=./inventory
collections_paths = /home/rothakur/ansible-collections/collections

[persistent_connection]
command_timeout = 100
connect_timeout = 100
connect_retry_timeout = 100
```

##### STEPS TO REPRODUCE

```yaml
- name: Merged Playbook
  hosts: iosxr-lab
  gather_facts: no
  collections:
    - cisco.iosxr
  tasks:
    - name: Merge the provided interfaces config to running-config
      iosxr_interface:
        name: 'GigabitEthernet0/0/0/0'
        description: 'interface is configures demo1'
```

##### EXPECTED RESULTS

the description should be updated with  'interface is configured demo1'

##### ACTUAL RESULTS

```paste below
fatal: [10.8.38.70]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "active": "active",
            "aggregate": null,
            "delay": 10,
            "description": "interface is configures demo1",
            "duplex": null,
            "enabled": true,
            "mtu": null,
            "name": "GigabitEthernet0/0/0/0",
            "provider": null,
            "rx_rate": null,
            "speed": null,
            "state": "present",
            "tx_rate": null
        }
    },
    "msg": "b\"'GetReply' object has no attribute 'strip'\""
}

```
